### ISSUE TITLE
AHK script depends on other scripts

### ISSUE THREAD

**Issue by loopernow** [justcla/WindowHotKeys#11]
Very cool. I have Autohotkey, so I downloaded the AHK. But it has an include line (line 23) to another AHK file.

So I downloaded the source zip which included everything needed, and was able to run the AHK that way.

Not sure if this is really an "issue;" I'm not super-familiar with Github. I'm just noting that I don't think the documentation is very clear for casual Autohotkey users that you can't really just download the AHK and go.

**Comment by justcla** [comment]
Yeah, it works best when using the ini files plus the menu icon, and the other settings files, so I created the packaged installer to give you everything.
Or, if you're planning development, it's best to clone the whole repo (it's not very big).

I could add a note that the main auto hot key file won't work by itself.

**Comment by justcla** [comment]
I notice the Readme says, right up at the start:

Download the Installation Wizard

Download the **Installation Wizard**
- Download the [Windows installer MSI](https://github.com/justcla/WindowHotKeys/raw/master/Packaging/Move%20and%20Resize%20Hotkeys.msi)
- Note MSI Windows Installer installs the EXE plus additional shortcut profiles and config file.
- Also installs system tray icon with access to settings.

*Alternatively* - to just get the EXE (no extra profiles and config files):
- Download and run the executable [Move and Resize Hotkeys.exe](https://github.com/justcla/WindowHotKeys/raw/master/Move%20and%20Resize%20Hotkeys.exe)

**Comment by justcla** [comment]
I updated the Release Notes text to indicate that the AHK file needs other files to run, and that people should pull the whole repo.
