### ISSUE TITLE
can not work on app windows terminal

### ISSUE THREAD

**Issue by lost22git** [justcla/WindowHotKeys#9]

**Comment by justcla** [comment]
More information required. Please provide some paragraphs of descriptions so I can get a better of idea of:
- What OS you are using
- What issues you are having
- What you have tried
- What you were expecting
- How did you install it
- Were there any error messages
- What do you see?

**Comment by justcla** [comment]
And...what do you mean by "app windows terminal"?
And what does "can not work" mean?

**Comment by lost22git** [comment]
* os => win11
* issue => can not move or resize window of [windows terminal](https://github.com/microsoft/terminal)
* installing way => run exe file directly
* reproduce gif
![动画3](https://user-images.githubusercontent.com/65008815/212552134-26cbda9a-ae16-4a1e-bbab-642bffaf8a89.gif)

**Comment by justcla** [comment]
Thanks for the info and the repro video.

That's odd. I am using Win11 and it works perfectly when I try to move or resize my Terminal window.

I notice that your Terminal looks slightly different to mine. I'm running the one from the Microsoft Store - the same that you linked to.

This is my repro:

https://user-images.githubusercontent.com/17131343/212553238-efe0612d-d73f-4b90-ab33-1e5af3f27d9a.mp4

**Comment by lost22git** [comment]
my wt version:

![Screenshot 2023-01-16 004341](https://user-images.githubusercontent.com/65008815/212554544-78bdee0b-c098-48d1-8a2b-a46cb6c5190a.png)

**Comment by justcla** [comment]
I'm on Windows Terminal Version: 1.15.3466.0
Although, I'm not sure that is the issue.

I wonder if there's something specific to the Shell you are running, that might be taking priority of the key-capture events.
Windows Terminal defines a whole bunch of shortcuts. Could there be a conflict there?
Also, some keyboards will trigger AltGr if the right Alt is pressed, or if the right Ctrl+Alt are pressed together (this is coded into Visual Studio).

Can you try it with another shell? Try Alt-Tab out and back again and see if the focus moves to the window instead of the shell.

How did you find out about this tool, by the way? I thought I was the only one using it. 🤣

**Comment by lost22git** [comment]
i upgrade it and it works now ：）

![Screenshot 2023-01-16 004341](https://user-images.githubusercontent.com/65008815/212596476-d593f533-58cb-4a68-85b7-1682c78bdb86.png)

I had hoped that PowerToys would include this feature, but it doesn't seem to be in the plan.

https://github.com/microsoft/PowerToys/issues/23345 🤣

Finally, thanks for you help and good job.

**Comment by justcla** [comment]
Well that's good news. Glad I could help.

But seriously, how did you discover this tool?

**Comment by lost22git** [comment]
via github search :)

https://github.com/search?o=desc&q=move+and+resize+windows&s=updated&type=Repositories

**Comment by justcla** [comment]
Fascinating. I was just thinking of renaming my tool to "Move and Resize Windows".
Now that I see your search query, I think I've found the most appropriate name for the tool. ;-)
Thanks. Enjoy the tool!

**Comment by lost22git** [comment]
@justcla  

I found it can't work, as long as the window started by Start-Process

**Comment by lost22git** [comment]
The real cause of this problem is permissions. Run the app with administrator privileges to work.
